---
- name: Define apt repos
  loop: "{{ hetzner_repos }}"
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    filename: "{{ hetzner_filename }}"
    update_cache: "{{ hetzner_update_cache }}"
    state: present
  tags:
    - hetzner

...
